name: test

on:
  push:
    branches: "master"
  pull_request:
    branches: master
  schedule:
    - cron: '0 0 * * 6'


jobs:

  lint-black:
    name: black-formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black
        run: |
          python -m pip install black
      - name: Black Code Formatter
        run: |
          black --check .

  full_test:
    name: run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: python -m pip install -r dev-requirements.txt
      - name: Install package
        run: |
          python -m pip install .
      - name: Run tests
        run: pytest intake_pangaeapy -v --cov --cov-report term-missing
